<?php declare(strict_types=1);

namespace Drenso\PhanExtensions\Visitor\Annotation\Base;

require_once __DIR__ . '/../../../Helper/NamespaceChecker.php';

use Drenso\PhanExtensions\Helper\NamespaceChecker;
use Phan\PluginV2\PluginAwarePostAnalysisVisitor;
use ast\Node;

/**
 * Class AnnotationVisitor
 *
 * {@inheritdoc}
 *
 * @author BobV
 */
abstract class AnnotationVisitor extends PluginAwarePostAnalysisVisitor
{
  /**
   * Holds the exceptions for a specific framework
   *
   * @var array
   */
  protected $exceptions = [];

  /**
   * Visit class
   *
   * @param Node $node
   *
   * @throws \AssertionError
   */
  public function visitClass(Node $node)
  {
    $this->checkDocComment($node);
  }

  /**
   * Visit method
   *
   * @param Node $node
   *
   * @throws \AssertionError
   */
  public function visitMethod(Node $node)
  {
    $this->checkDocComment($node);
  }

  /**
   * Visit property
   *
   * @param Node $node
   *
   * @throws \AssertionError
   */
  public function visitPropElem(Node $node)
  {
    $this->checkDocComment($node);
  }

  /**
   * Retrieves the docblock for the node, and checks for the given annotations
   *
   * @param Node $node
   *
   * @throws \AssertionError
   */
  private function checkDocComment(Node $node)
  {
    // Retrieve the doc block
    $docComment = $node->children['docComment'];

    // Ignore empty doc blocks
    if ($docComment === NULL || strlen($docComment) == 0) {
      return;
    }

    // Retrieve all annotations from the doc comment
    preg_match_all('/\s*\*\s*\@([A-Z][a-zA-Z]+)[\\\(]?/', $docComment, $matches);
    foreach ($matches[1] as $annotation) {
      // Check for exceptions
      if (in_array($annotation, $this->exceptions)) continue;

      // Check for annotation
      NamespaceChecker::checkVisitor($this, $this->code_base, $this->context, $annotation, 'AnnotationNotImported',
          'The classlike/namespace {CLASS} was never imported (generated by DrensoAnnotation plugin)');
    }
  }
}
